[package]
name = "libe2fs-sys"
description = "Rust bindings for libe2fs"
version = "0.2.18"
edition = "2021"
links = "ext2fs"
license = "Apache-2.0"
repository = "https://github.com/queer/flail"

[build-dependencies]
bindgen = "0.65.1"